apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcp-bridge.fullname" . }}
  labels:
    {{- include "mcp-bridge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mcp-bridge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mcp-bridge.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /mcp_bridge/config.json
              subPath: config.json
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "mcp-bridge.fullname" . }}-config